<script lang="ts">
	import { Badge } from '$lib/components/ui/badge/index.js';
	import { Button } from '$lib/components/ui/button/index.js';
	import * as Dialog from '$lib/components/ui/dialog/index.js';
	import { downloadImage } from '$lib/download.js';
	import { history, type GenerationResult } from '$lib/history.svelte.js';
	import DownloadIcon from '@lucide/svelte/icons/download';
	import TrashIcon from '@lucide/svelte/icons/trash-2';

	let preview = $state<GenerationResult | null>(null);
	let previewOpen = $state(false);

	function openPreview(item: GenerationResult) {
		preview = item;
		previewOpen = true;
	}
</script>

{#if history.items.length > 0}
	<div class="space-y-3">
		<div class="flex items-center justify-between">
			<span class="font-mono text-xs text-muted-foreground">history ({history.items.length})</span>
			<Button
				variant="ghost"
				size="sm"
				onclick={() => history.clear()}
				class="h-7 gap-1 font-mono text-xs text-muted-foreground"
			>
				<TrashIcon class="size-3" />
				clear all
			</Button>
		</div>

		<div class="grid grid-cols-3 gap-3">
			{#each history.items as item (item.id)}
				<div class="group relative overflow-hidden border border-border">
					<button
						type="button"
						onclick={() => openPreview(item)}
						class="block w-full cursor-zoom-in text-left focus-visible:ring-2 focus-visible:ring-ring focus-visible:outline-none focus-visible:ring-inset"
						aria-label={`Preview image generated by ${item.modelName}`}
					>
						<img src={item.imageUrl} alt={item.prompt} class="w-full object-cover" loading="lazy" />
					</button>

					<div
						class="pointer-events-none absolute inset-0 flex flex-col justify-between bg-black/60 p-2 opacity-0 transition-opacity group-focus-within:opacity-100 group-hover:opacity-100"
					>
						<p class="line-clamp-3 font-mono text-xs text-white">{item.prompt}</p>

						<div class="flex items-center justify-between">
							<div class="flex flex-col gap-0.5">
								<span class="font-mono text-[10px] text-white/60">{item.modelName}</span>
								{#if item.cost !== null}
									<Badge variant="secondary" class="w-fit font-mono text-[10px]">
										${item.cost.toFixed(4)}
									</Badge>
								{/if}
							</div>
							<div class="pointer-events-auto flex gap-1">
								<button
									onclick={() => downloadImage(item.imageUrl, `imagen-${item.timestamp}.png`)}
									class="flex size-6 items-center justify-center text-white/80 hover:text-white"
									aria-label="Download"
								>
									<DownloadIcon class="size-3.5" />
								</button>
								<button
									onclick={() => history.remove(item.id)}
									class="flex size-6 items-center justify-center text-white/80 hover:text-white"
									aria-label="Delete"
								>
									<TrashIcon class="size-3.5" />
								</button>
							</div>
						</div>
					</div>
				</div>
			{/each}
		</div>
	</div>
{/if}

<Dialog.Root bind:open={previewOpen}>
	{#if preview}
		<Dialog.Content
			class="max-h-[92vh] max-w-[calc(100%-2rem)] gap-0 overflow-y-auto p-0 sm:max-w-5xl md:overflow-hidden"
		>
			<Dialog.Header class="border-b border-border p-4 pr-12">
				<Dialog.Title>{preview.modelName}</Dialog.Title>
				<Dialog.Description class="line-clamp-2">{preview.prompt}</Dialog.Description>
			</Dialog.Header>

			<div class="grid min-h-0 md:grid-cols-[minmax(0,1fr)_18rem]">
				<div class="flex min-h-0 items-center justify-center bg-black">
					<img
						src={preview.imageUrl}
						alt={preview.prompt}
						class="max-h-[65vh] w-full object-contain md:max-h-[calc(92vh-5rem)]"
					/>
				</div>

				<div class="flex flex-col gap-4 border-t border-border p-4 md:border-t-0 md:border-l">
					<dl class="flex flex-col gap-3 text-xs">
						<div class="flex items-center justify-between gap-4">
							<dt class="text-muted-foreground">size</dt>
							<dd class="font-mono">{preview.size}</dd>
						</div>
						<div class="flex items-center justify-between gap-4">
							<dt class="text-muted-foreground">created</dt>
							<dd class="text-right font-mono">
								{new Date(preview.timestamp).toLocaleString()}
							</dd>
						</div>
						{#if preview.cost !== null}
							<div class="flex items-center justify-between gap-4">
								<dt class="text-muted-foreground">cost</dt>
								<dd><Badge variant="secondary">${preview.cost.toFixed(4)}</Badge></dd>
							</div>
						{/if}
					</dl>

					<Button
						onclick={() => downloadImage(preview!.imageUrl, `imagen-${preview!.timestamp}.png`)}
						class="mt-auto w-full"
					>
						<DownloadIcon data-icon="inline-start" />
						download
					</Button>
				</div>
			</div>
		</Dialog.Content>
	{/if}
</Dialog.Root>
